sudo: required
services:
- docker
matrix:
  include:
  - language: python
    python: 3.5
    install:
    - pip install -r backend/requirements.txt
    - pip install pylint
    - pip install coverage
    - pip install flake8
    - pip install pep8-naming
    before_script:
    - cd backend
    script:
    - flake8 ./
    - pylint backend
    - coverage run --source backend -m unittest discover
    - coverage report
    before_deploy:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin
    - chmod +x $TRAVIS_BUILD_DIR/remote_deploy.sh
    - cd $TRAVIS_BUILD_DIR
    deploy:
      provider: script
      skip_cleanup: true
      script: sh $TRAVIS_BUILD_DIR/remote_deploy.sh
      on:
        branch: master
  - language: node_js
    node_js: 7
    install:
    - cd $TRAVIS_BUILD_DIR/frontend
    - npm install
    - cd $TRAVIS_BUILD_DIR
    before_script:
    - cd $TRAVIS_BUILD_DIR/frontend
    script:
    - npm test
env:
  global:
  - secure: Zz6n7SZz+a2eSjy6WVF6HFIQM0iYPm4NuCm+e/xGVLyNeDTOR3kGMgjXr7Z4g0HXxRZaD9ZaaP6r4rMC2i66Hy9BuQINrnqJTCr61nHEl9Z2VRM2INoA3yA7NgrGmwjE4t/WObwpCceJfmSD58bDCEX/WGo5MzqnspssLIznjjFTHNK/X0Q4fLtZPbYroSoG3EFeyoB67fa7CpqcWU0OVO6sQyMrAZmEFiAzVtAgzJ3ZAkGRMXrNMR8HQTKedxXBNAesQXBd1lsq78e+9R+qGhODvldJ541M/yCBXBNZZazGDtrlccbEPj+MfZ4H2xHgh2qKrAk/s2jMiIKtZ6XzdJxejmUtenoc6fXphMLHy6PxtgSd6KvkQLWXGFXWhc1YWtNoxGleqxjerrFyh6x3EakjCqL3Ec2IsI0D6ihjP6nrbBSBWQ9i8g5LVUpFWbLGACQ7T5tZKeUFU2hBWuvguyvpLRxOa/raMMcVwlrJoGhLk+3pSA8/9x/q9/XukBTW60eW59t+kPtZtX7A86J7/04Ok/yDww/J+t8bP52f5n+vpDqZZgZY1TimBp5CR5RJ1uzq7p9u0YS9ewMkulGjQQ4KsLAPWSKMa8RfYaVsACJvqbYmK9H0wJeEPMCgqwpiUR2EzqS3HOfh6jP141GEUCdvZpnVsVg+4WzKQe6VdIk=
  - secure: OnXo/dpwDHIttV3EdBwI2CeDA7tnxlP++uchntbNiIEwoHbl1IDaGgFNJaEg+EiQwRtqcMnEvax6KKc6r6zTfwx0EaWxFtBnAZqcze8d+12pa6x/nYFhNljI7GMQhcKDbHRN6dbh4UE7aLYZ2I1BIAh1R63VyzNWwzIJL2vbnaZc9qH6mSH5ojuOTuiCjKLCOPI0g2vlY2foWihU+DWJujf+bqMFpqLWOfy4bJhlPWkrLre4kQXZO4fx5eZUfB7agxDv8RfrnLXcsMIWMt7we/sgyfMPNUl0WEMKYQR4qKFU2qvEjJMWfR/cg4RTGFhWYqdoF5LngcA4tFQCa+hhl1XKYp1kD2EJlCrWr/MdKiq2pof6Xb+ZlcpZXSQw8VtrybhlVGCEMpGVyW3oUJVVoHJqz0dZxHJe4N5sXss7pODIDqgWJC/mVajdL1cx3OkgCU6eZnxLE/H4GgZbf+6w9OMYUeCmEkIzzMgkUCAPzzUcnCcEVUByTQxEYNc6fcty+aMaL9nFGGgdtIQ4EFml0fLOSayrTJn49RTfv1IB3AuBQi0FEP/T3XuFZRwiUnSzv0xlizA1lVXBPtiZasLvHqoj3tdwVX8R4iC4L+tyM17W7QdiXpOsZWSZCtfpVZrEhlNikgEOzGyjVkdXThseKQhHJO69WoFEkcaz05WkwXo=
